"""
CoarseSteering14: coarse group steering over the full (still rank-deficient)
actuation matrix — the 14-robot generalisation of ``capswitcher``'s primitive.

A single coarse control of move-group ``g`` has two physical parts:

1. **Rotation.** All robots rotate according to the actuation matrix ``A``
   (columns = complements of the *original* groups + the all-ones empty-group
   column).  ``A`` has rank ``K`` (5 for 14 robots) which is far below ``N``,
   so the reachable rotation subspace is low-dimensional — the rank-deficiency
   problem arises naturally and **no column is dropped** (unlike the 6-robot
   system's artificial rank-2 reduction).  With no random drop the whole coarse
   control is a *deterministic* function of (state, group): no seed threading,
   and ``pinv(A)`` is precomputed once.

       least-squares heading:   t* = pinv(A) @ dθ_desired
       nonlinear progress:      t* = argmax  Σ_members  Δdistance_to_goal(t)

   and apply ``dθ_actual = A @ t*`` to every robot.

2. **Move.** Only the *members* of the chosen move-group advance forward by the
   group's configured translation length ``move_distances[group]``; non-members
   hold still.

Move-groups vs actuation columns
--------------------------------
Unlike the 6-robot system, the selectable move-groups are **not** the actuation
columns: they are the 22 subgroups (sizes 3/4/7) generated by the binary group
algebra in ``group_generator.py``.  The rotation phase always uses the full
``A``; the chosen group only decides who translates (and therefore the step
cost and the achievable progress).

Frame format, sub-step splitting and the ``move_distance`` / ``lin_max``
distinction are identical to ``capswitcher.policies.coarse_steering`` — see
that module's docstring for the physical discussion.
"""

from __future__ import annotations

import time

import numpy as np
from scipy.optimize import minimize


def _angle_wrap(angle: np.ndarray) -> np.ndarray:
    """Wrap angles into (−π, π]."""
    return (angle + np.pi) % (2.0 * np.pi) - np.pi


class CoarseSteering14:
    """
    Coarse group steering for a swarm of coupled unicycle robots.

    Args:
        A_full:        (N, K) actuation matrix; ``A[i, s] = 1`` means robot ``i``
                       rotates when actuation column ``s`` is driven.  Used whole —
                       never reduced.
        move_groups:   List of member index arrays — the selectable coarse
                       move-groups (0-based ids are positions in this list).
        move_distance: Coarse translation length (metres) per control — a scalar
                       applied to every group, or a ``{group_id: distance}``
                       mapping covering every selectable group (e.g.
                       ``SwitcherCost.move_distances``). Default 0.5.
        method:        ``"least_squares"`` (pinv heading) or ``"nonlinear"``
                       (maximise members' distance-to-goal reduction).
        step_time:     Simulator step duration (s). Default 0.3.
        ang_max:       Max angular velocity magnitude (rad/s). Default 1.0.
        lin_max:       Max linear velocity (m/s). Default 0.5.
    """

    def __init__(
        self,
        A_full: np.ndarray,
        move_groups: list,
        move_distance: float | dict = 0.5,
        method: str = "least_squares",
        step_time: float = 0.3,
        ang_max: float = 1.0,
        lin_max: float = 0.5,
    ) -> None:
        if method not in ("least_squares", "nonlinear"):
            raise ValueError(
                f"method must be 'least_squares' or 'nonlinear' (got {method!r})."
            )
        self.A_full = np.asarray(A_full, dtype=np.float64)
        if self.A_full.ndim != 2:
            raise ValueError(f"A_full must be 2-D (got shape {self.A_full.shape}).")
        self.num_robots = int(self.A_full.shape[0])

        self._members = [np.asarray(g, dtype=int) for g in move_groups]
        if not self._members:
            raise ValueError("move_groups must be non-empty.")
        for g in self._members:
            if g.size == 0:
                raise ValueError("every move-group must have at least one member.")
            if g.min() < 0 or g.max() >= self.num_robots:
                raise ValueError(f"move-group {g.tolist()} out of range for N={self.num_robots}.")

        group_ids = range(len(self._members))
        if isinstance(move_distance, dict):
            missing = [g for g in group_ids if g not in move_distance]
            if missing:
                raise ValueError(f"move_distance mapping missing groups {missing}")
            self.move_distances = {g: float(move_distance[g]) for g in group_ids}
        else:
            self.move_distances = {g: float(move_distance) for g in group_ids}
        if any(d < 0.0 for d in self.move_distances.values()):
            raise ValueError("move_distance must be non-negative")
        self.method = method
        self.step_time = float(step_time)
        self.ang_max = float(ang_max)
        self.lin_max = float(lin_max)

        self._pinv_A = np.linalg.pinv(self.A_full)

        # Wall-clock seconds spent in the most recent rotation solve.
        self.last_solve_time_s: float = 0.0

    # ------------------------------------------------------------------

    def selectable_groups(self) -> list[int]:
        """0-based ids of all selectable move-groups."""
        return list(range(len(self._members)))

    def members_of(self, group: int) -> np.ndarray:
        """Robot indices that move when move-group ``group`` (0-based) is chosen."""
        return self._members[group]

    # ------------------------------------------------------------------

    def _solve_rotation(
        self,
        theta_current: np.ndarray,
        d_theta_desired: np.ndarray,
        px: np.ndarray,
        py: np.ndarray,
        gx: np.ndarray,
        gy: np.ndarray,
        members: np.ndarray,
        move_distance: float,
    ) -> np.ndarray:
        """
        Solve for the per-robot rotation ``dθ_actual = A @ t*`` (full matrix).

        Times the solve into ``self.last_solve_time_s``.
        """
        t0_clock = time.perf_counter()

        t_ls = self._pinv_A @ d_theta_desired  # (K,)

        if self.method == "least_squares":
            t_star = t_ls
        else:
            d = move_distance
            pm = np.stack([px[members], py[members]], axis=1)        # (Nm, 2)
            gm = np.stack([gx[members], gy[members]], axis=1)        # (Nm, 2)
            theta_m = theta_current[members]                          # (Nm,)
            A_m = self.A_full[members, :]                             # (Nm, K)
            dist0 = np.linalg.norm(gm - pm, axis=1)                   # (Nm,)

            def neg_progress(t: np.ndarray) -> float:
                theta_new = theta_m + A_m @ t                         # (Nm,)
                p_new = pm + d * np.stack(
                    [np.cos(theta_new), np.sin(theta_new)], axis=1
                )
                dist1 = np.linalg.norm(gm - p_new, axis=1)
                return float(-np.sum(dist0 - dist1))                  # maximise progress

            res = minimize(neg_progress, t_ls, method="BFGS")
            t_star = res.x

        d_theta_actual = self.A_full @ t_star  # (N,)
        self.last_solve_time_s = time.perf_counter() - t0_clock
        return d_theta_actual

    # ------------------------------------------------------------------

    def compute_actions(
        self, robot_state: np.ndarray, group: int
    ) -> tuple[list[list[list[float]]], list[list[float]]]:
        """
        Compute the sim-input action frames for one coarse control of ``group``.

        Deterministic given (state, group): the full actuation matrix is used, so
        there is no random column drop and no seed parameter.

        Args:
            robot_state: (N, 11) state, same column layout as the 6-robot system
                (0,1: px,py; 2,3: cosθ,sinθ; 9,10: gx,gy).
            group: 0-based move-group id (see :meth:`selectable_groups`).

        Returns:
            rotation_frames, translation_frames — same frame format as
            ``capswitcher``: lists of per-robot ``[lin, ang]`` sim-input pairs.
        """
        if group not in range(len(self._members)):
            raise ValueError(
                f"group {group} is not selectable; "
                f"choose from 0..{len(self._members) - 1}."
            )

        s = np.asarray(robot_state, dtype=np.float64)  # (N, 11)
        px, py = s[:, 0], s[:, 1]
        cos_h, sin_h = s[:, 2], s[:, 3]
        gx, gy = s[:, 9], s[:, 10]

        theta_current = np.arctan2(sin_h, cos_h)              # (N,)
        theta_desired = np.arctan2(gy - py, gx - px)          # (N,)
        d_theta_desired = _angle_wrap(theta_desired - theta_current)  # (N,)

        members = self._members[group]
        move_distance = self.move_distances[group]
        d_theta_actual = self._solve_rotation(
            theta_current, d_theta_desired, px, py, gx, gy, members, move_distance
        )

        # ---- Rotation sub-steps (split to respect ang_max) ----------------
        max_abs = float(np.max(np.abs(d_theta_actual))) if d_theta_actual.size else 0.0
        max_per_step = self.ang_max * self.step_time
        rotation_frames: list[list[list[float]]] = []
        if max_abs > 1e-9:
            n_rot = int(np.ceil(max_abs / max_per_step))
            ang_vels = d_theta_actual / (n_rot * self.step_time)
            ang_vels = np.clip(ang_vels, -self.ang_max, self.ang_max)
            frame = [[0.0, float(ang_vels[i])] for i in range(self.num_robots)]
            rotation_frames = [list(map(list, frame)) for _ in range(n_rot)]

        # ---- Translation sub-steps (split to respect lin_max) -------------
        member_set = set(int(i) for i in members)
        max_per_step_lin = self.lin_max * self.step_time
        translation_frames: list[list[list[float]]] = []
        if move_distance > 1e-9:
            n_trans = int(np.ceil(move_distance / max_per_step_lin))
            lin_cmd = move_distance / (n_trans * self.step_time)
            lin_cmd = min(lin_cmd, self.lin_max)
            frame = [
                [lin_cmd if i in member_set else 0.0, 0.0]
                for i in range(self.num_robots)
            ]
            translation_frames = [list(map(list, frame)) for _ in range(n_trans)]

        return rotation_frames, translation_frames
