"""
Canonical 14-robot instantiation constants and factories.

Everything derives from the binary group algebra with ``m = 4`` original
groups (``policies/group_generator.py``): robots are the 14 non-trivial binary
codes 1..14, original group ``j`` is the set of robots with bit ``j`` set.

* **Actuation matrix** ``A_FULL`` (14 × 5): one column per original group —
  the *complement* of its membership (non-members rotate) — plus the all-ones
  column of the empty group (every robot rotates).  rank(A_FULL) = 5 < 14: the
  system is naturally rank-deficient, no artificial reduction is applied.
* **Move-groups** ``MOVE_GROUPS`` (22): all subgroups of size 3, 4 and 7
  generated by the algebra — 6 size-3, 12 size-4, 4 size-7 — sorted by
  (size, indices).  Their 0-based list positions are the coarse action ids
  used everywhere (search, decision dicts, logged shards).
"""

from __future__ import annotations

import numpy as np

from robot_nav.models.MARL.capswitcher_14.policies.coarse_steering import (
    CoarseSteering14,
)
from robot_nav.models.MARL.capswitcher_14.policies.group_generator import (
    generate_all_groups,
    generate_original_groups,
)

N_ROBOTS = 14
M_ORIGINAL = 4
MOVE_GROUP_SIZES = (3, 4, 7)


def build_actuation_matrix() -> np.ndarray:
    """(14, 5) actuation matrix: [h_1 .. h_4, 1] — complements + empty group."""
    h_vectors, _ = generate_original_groups(M_ORIGINAL, N_ROBOTS)
    ones = np.ones(N_ROBOTS, dtype=int)
    return np.stack([*h_vectors, ones], axis=1).astype(np.float64)


def build_move_groups() -> list[list[int]]:
    """The 22 coarse move-groups (sizes 3/4/7), sorted by (size, indices)."""
    groups = generate_all_groups(m=M_ORIGINAL, n=N_ROBOTS, use_complement=True)
    kept = [g for g in groups if len(g) in MOVE_GROUP_SIZES]
    kept.sort(key=lambda g: (len(g), g))
    return kept


A_FULL: np.ndarray = build_actuation_matrix()
MOVE_GROUPS: list[list[int]] = build_move_groups()
N_MOVE_GROUPS: int = len(MOVE_GROUPS)  # 22


def make_coarse_steering(
    move_distance: float | dict = 0.5,
    method: str = "least_squares",
    step_time: float = 0.3,
    ang_max: float = 1.0,
    lin_max: float = 0.5,
) -> CoarseSteering14:
    """The canonical 14-robot coarse primitive over ``A_FULL`` / ``MOVE_GROUPS``."""
    return CoarseSteering14(
        A_full=A_FULL,
        move_groups=MOVE_GROUPS,
        move_distance=move_distance,
        method=method,
        step_time=step_time,
        ang_max=ang_max,
        lin_max=lin_max,
    )
